[package]
name = "ece-crypto-openssl"
version = "0.1.0"
authors = ["Edouard Oger <eoger@fastmail.com>"]
license = "MPL-2.0"

[dependencies]
hkdf = "0.6"
lazy_static = "1.1.0"
openssl = "0.10"
sha2 = "0.7"

[dependencies.ece-crypto]
path = "../"
